name: hello-world
on: [push]
jobs:
  Run_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Get node version
        run: node -v
      - name: Run hello world
        run: node hello-world.js
